INSERT INTO
    users (
        name,
        phone,
        email,
        address,
        gender,
        username,
        password,
        created_at,
        role
    )
VALUES
    (
        'ha',
        '08123456789',
        'ha@ha',
        '',
        'male',
        'ha',
        'ha',
        '2021-01-01',
        'admin'
    ),
    (
        'he',
        '08123456789',
        'he@he',
        '',
        'male',
        'he',
        'he',
        '2021-01-01',
        'user'
    ),
    (
        'hi',
        '08123456789',
        'hi@hi',
        '',
        'female',
        'hi',
        'hi',
        '2021-01-01',
        'user'
    ),
    (
        'ho',
        '08123456789',
        'ho@ho',
        '',
        'male',
        'ho',
        'ho',
        '2021-01-01',
        'user'
    ),
    (
        'hu',
        '08123456789',
        'hu@hu',
        '',
        'male',
        'hu',
        'hu',
        '2021-01-01',
        'user'
    );